### ISSUE TITLE
 Unable to initialize libusb: 99 Other error

### ISSUE THREAD

**Issue by gitechsiva** [usb4java/usb4java#48]
Dear Friends,
        I am trying usb4java for USB printer. When I run my java Program i got the following error.

/root$ java -jar 1USBPrint.jar
libudev: udev_monitor_new_from_netlink_fd: error getting socket: Invalid argument
Exception in thread "main" org.usb4java.LibUsbException: USB error 99: Unable to initialize libusb: Other error
at usbprint.UsbLowPos.findDevice(UsbLowPos.java:98)
at usbprint.UsbLowPos.claimDevice(UsbLowPos.java:39)
at usbprint.UsbLowPos.main(UsbLowPos.java:54)

Please check and suggest for the solution

**Comment by kayahr** [comment]
usb4java 1.3.0 was released today which now uses libusb 1.0.22 which may have fixed this issue. Please try again with this new version and give feedback here if the exact same problem still occurs. If it still doesn't work but it is not the exact same result then please open a new issue.
