### ISSUE TITLE
NullPointerException at AbstractIrpQueue.add()

### ISSUE THREAD

**Issue by lucasdall** [usb4java/usb4java#54]
Hi,

I'm using usb4java to integrate a Datamax e4205A Printer to my java POS System. Eventualy, the printer throws a NPE described below:

```
Caused by: java.lang.NullPointerException
    at de.ailis.usb4java.AbstractIrpQueue.add(AbstractIrpQueue.java:75)
    at de.ailis.usb4java.Pipe.asyncSubmit(Pipe.java:197)
    at de.ailis.usb4java.Pipe.syncSubmit(Pipe.java:184)
    at com.gomait.device.printer.io.DatamaxNewIO.sendData(DatamaxNewIO.java:98)
```

Someone has gone through a similar problem?

Thanks,
Lucas

**Comment by kayahr** [comment]
usb4java 1.3.0 was released today which now uses libusb 1.0.22 which may have fixed this issue. Please try again with this new version and give feedback here if the exact same problem still occurs. If it still doesn't work but it is not the exact same result then please open a new issue.
